tree_names = {
    'P': 'paprastoji pušis',
    'Pk': 'kalninė pušis',
    'Pb': 'Bankso pušis',
    'Pj': 'juodoji pušis',
    'Kd': 'kedras',
    'E': 'eglė',
    'M': 'maumedis',
    'Pc': 'pocūgė',
    'Kn': 'kėnis',
    'Ks': 'kiti',
    'Ą': 'ąžuolas',
    'Ąr': 'raudonasis ąžuolas',
    'U': 'uosis',
    'K': 'klevas',
    'Sb': 'skroblas',
    'G': 'guoba',
    'S': 'skirpstas',
    'Bu': 'bukas',
    'V': 'vinkšna',
    'Kk': 'kiti kietieji',
    'B': 'beržas',
    'J': 'juodalksnis',
    'L': 'liepa',
    'D': 'drebulė',
    'Bt': 'baltalksnis',
    'T': 'tuopa',
    'Gl': 'gluosnis',
    'Bl': 'blindė',
    'Km': 'kiti minkštieji'
}

liquid_t = {
    'P': 87,
    'PK': 87,
    'PB': 85,
    'PJ': 85,
    'KD': 85,
    'E': 85,
    'M': 85,
    'PC': 85,
    'KN': 85,
    'KS': 85,
    'Ą': 85,
    'ĄR': 84,
    'U': 85,
    'K': 85,
    'SB': 85,
    'G': 85,
    'S': 85,
    'BU': 85,
    'V': 85,
    'KK': 85,
    'B': 83,
    'J': 83,
    'L': 85,
    'D': 87,
    'BT': 88,
    'T': 85,
    'GL': 85,
    'BL': 85,
    'KM': 85
}

